### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jyc** [white-pony/go-fann#10]
Hello,

Thanks for the useful library? Would you be able to include a LICENSE file? I presume that the project is open-source, but without a license stated by the author the code is technically 'all rights reserved.'

Thanks again!
Jonathan Chan

**Comment by white-pony** [comment]
Hello,

Thank you for interest!  Sure, please, feel free to send PR with license
file, if you already have it somewhere. If not, I'll look into license of
original project.

Thanks.

**Comment by jonathanyc** [comment]
Hello,

Thanks for the quick reply! The original FANN library seems to be licensed under the LGPL v2.1, but as far as I understand it (though I'm not a lawyer) you're allowed to choose any license for these bindings, as they are your original code. You could add a license file to your project containing the [LGPL v2.1](https://www.gnu.org/licenses/lgpl-2.1.txt), like FANN, or you could choose a different license, like the [BSD](http://opensource.org/licenses/BSD-2-Clause).

Hope this helps! Again, I really appreciate you having written this library. It has saved me a lot of trouble.

**Comment by vksnk** [comment]
Thanks, that was helpful. I've added license file (I think it's MIT license), please, let me know, if it does not work for you.
